name: Release

on:
  push:
    tags:
      - v*.*.*

run-name: Release ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: NuGet restore
        run: nuget restore ReControl.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution (Release)
        run: msbuild ReControl.sln -m -p:Configuration=Release

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          path: ReControl.Package/bin/x64/Release/en-US/*.msi

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download installer
        uses: actions/download-artifact@v4

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          args: --current

      - name: Trim changelog
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          tail -n +3 git-cliff/CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: ${{ env.RELEASE_BODY }}
          files: artifact/*.msi
